---
name: module3_task1
on:
  push: null
  schedule:
    - cron: 0 0 * * *
jobs:
  build:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: ./module3_task1
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
          sudo ./setup.sh
      - name: make-help
        run: |
          make help
      - name: make-build
        run: |
          make build
      - name: make-post
        run: |
          make POST_NAME=who-are-we POST_TITLE="Who are we" post 
      - name: make-clean
        run: |
          make clean
          ls