name: module3_task1

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: ./module3_task0
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
            pwd
