name: module3_task1

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - run: |
      cd ./module3_task0/
      ./setup.sh
      make build
      make clean
      make help
